### ISSUE TITLE
Credits/Quellen

### ISSUE THREAD

**Issue by sommergeo** [FlorianDiller/CodingDaVinci#29]
Hallo zusammen, wir sollten noch irgendwo die Datenquellen unterbringen. Es muss nicht zwingend direkt im Spiel sein, aber sie grundsätzlich aufzuführen ist sicher angebracht. Ich fange hier mal mit den Geodaten an:

- ETOPO1 Global Relief Model from NOAA NCEI [doi:10.7289/V5C8276M](https://dx.doi.org/10.7289/V5C8276M) 
- Hypsometric map 1:50M and inland water bodies1:50M from Natural Earth, [naturalearthdata.com](https://www.naturalearthdata.com)
- ROCEEH Out of Africa Database from [www.roceeh.uni-tuebingen.de/roadweb/](https://www.roceeh.uni-tuebingen.de/roadweb/)

Die DOI von ETOPO1 funktioniert nicht, wird aber von der Quelle ausdrücklich verlangt.

**Comment by FlorianDiller** [comment]
Ist im Anfangstitel mit eingebunden
